# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: openCOSMO-RS Book
author: Priscilla Ensley, Simon Müller, Edgar Sanchez
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# In _config.yml
sphinx:
  extra_extensions:
    - sphinxcontrib.bibtex
  config:
    bibtex_bibfiles: ["references.bib"]
    bibtex_reference_style: super

    
# Information about where the book exists on the web
repository:
  url: https://github.com/PriscillaEnsleySolis/openCOSMO_RS_Book
  path_to_book: docs
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  baseurl: /openCOSMO_RS_Book
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - substitution
    - smartquotes
    - tasklist
    - fieldlist
    - attrs_inline
    - attrs_block
